test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.0b1c3be0.name = "Upgrade from 1.16.2"

    test_upgrade_from.722ade2a.name = "Upgrade from 1.19.2"
