#!/bin/bash
app=$1
new_users=$2
app_path=/var/www/$app

# Source app helpers
. /usr/share/yunohost/helpers


if [[ "freshrss" = "$app" ]];
then
    for myuser in $(echo "$new_users" | sed "s/,/ /g")
    do
        user_token=$(ynh_string_random)
        $app_path/cli/create-user.php --user $myuser --language en --token $user_token
        sudo chown -R www-data: $app_path/data/users/$myuser/
    done
fi
