#!/bin/bash
app=APPNAMETOCHANGE
app_path=/var/www/$app

myuser=$1

# Source app helpers
. /usr/share/yunohost/helpers

user_token=$(ynh_string_random)
sudo $app_path/cli/create-user.php --user $myuser --language en --token $user_token
sudo chown -R $app: $app_path/data/users/$myuser/
