#!/bin/bash
app=$YNH_APP_INSTANCE_NAME
app_path=/var/www/$app

myuser=$1

# Source app helpers
. /usr/share/yunohost/helpers

user_token=$(ynh_string_random)
sudo $app_path/cli/create-user.php --user $myuser --language en --token $user_token --no-default-feeds
sudo chown -R www-data: $app_path/data/users/$myuser/
