#!/usr/bin/env bash

set -a
source /usr/share/yunohost/helpers

app="${0//.\/50-}"
install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)
username=$1

sudo -u $app $install_dir/cli/delete-user.php --user $username
