#!/bin/bash

set -eu

# Source app helpers
. /usr/share/yunohost/helpers

# retrieve useful param
app=$YNH_APP_INSTANCE_NAME
path=/var/www/$app
dbpass=$(ynh_app_setting_get "$app" mysqlpwd)
domain=$(ynh_app_setting_get "$app" domain)

# Backup app files
ynh_backup "$path" "www"
# Backup conf files
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf" "nginx.conf"
ynh_backup "/etc/cron.d/$app" "cron"
ynh_backup "/etc/php/7.0/fpm/pool.d/$app.conf" "php-fpm.conf"

# Backup mysql
ynh_mysql_dump_db $app > $app.dmp
