#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

# this will most likely adjust NGINX config correctly
ynh_config_change_url_nginx

#=================================================
# UPGRADING FRESHRSS
#=================================================
ynh_script_progression "Upgrading $app..."

ynh_hide_warnings ynh_exec_as_app php$php_version "$install_dir/cli/reconfigure.php" --auth-type http_auth --environment production --base-url "https://$new_domain$new_path" --title FreshRSS --api-enabled --db-type mysql --db-host localhost --db-user "$db_name" --db-password "$db_pwd" --db-base "$db_name"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
