#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove the dedicated PHP-FPM config
ynh_config_remove_phpfpm

# Remove a cron file
ynh_safe_rm "/etc/cron.d/$app"

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

ynh_config_remove_fail2ban

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
