#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Source app helpers
. /usr/share/yunohost/helpers

db_user=freshrss
db_name=freshrss
domain=$(ynh_app_setting_get freshrss domain)

ynh_mysql_drop_db $db_name
ynh_mysql_drop_user $db_user

sudo rm -rf /var/www/freshrss
sudo rm -rf /etc/cron.d/freshrss
sudo rm -f /etc/nginx/conf.d/$domain.d/freshrss.conf

sudo service nginx reload
sudo yunohost app ssowatconf
